### ISSUE TITLE
Extension doesn't work anymore

### ISSUE THREAD

**Issue by tpysz5n** [abhutan1/Amazon-Whole-Foods-Delivery-Slots-Finder#2]
Hello again,

It is just me or Amazon has done something that stop this extension from working?
When I turn it on it just bring me to a page saying my cart is empty.
![image](https://user-images.githubusercontent.com/56814389/82008727-7d70c200-963b-11ea-9f4b-20f6bc53f337.png)
Thanks for reading. Take care!

**Comment by abhutan1** [comment]
Hey @tpysz5n, 

Thanks for flagging the bug. 

Amazon removed a string "Whole Foods Market" that the script was looking for to detect "Schedule Your Order" page. I removed this dependency. 

It should work now.

**Comment by tpysz5n** [comment]
Ah yes it works. You're amazing! Thanks!
